run:
  tests: true
linters:
  enable:
    - bodyclose
    - exportloopref
    - goimports
    - nilerr
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - tparallel
    - unconvert
    - unparam
    - whitespace
