name: "Close Stale Issues"
on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  cleanup:
    runs-on: ubuntu-latest
    name: "Close Stale Issues Job"
    steps:
    - uses: actions/stale@v4.1.1
      with:
        close-issue-message: This issue was closed due to inactivity. # optional
        days-before-issue-stale: 14 # optional
        days-before-pr-stale: -1 # optional
        exempt-draft-pr: true # optional, default is false

