name: Go
on:
  push:
  pull_request:
permissions:
  contents: read
  pull-requests: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Setup Go'
      uses: actions/setup-go@v4
      with:
        go-version: '>=1.21'
    - name: 'Checkout Repository'
      uses: actions/checkout@v3
    - name: 'Run tests'
      run: make tests
    - name: 'Build Vinegar'
      run: make VINEGAR_GOFLAGS="--tags nogui"
